spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/lms?createDatabaseIfNotExist=true
      username: root
      password: